---
abstract: 'Subscribe to Gmail feed'
author:
  - 'Masayoshi Sekimura <sekimura@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Gmail-Feed
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  Net::SSLeay: 0
  XML::Atom::Feed: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
